CREATE DATABASE IF NOT EXISTS loja_jogos;
USE loja_jogos;

CREATE TABLE IF NOT EXISTS editoras (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE,
    site VARCHAR(255),
    pais VARCHAR(60),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS plataformas (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE,
    fabricante VARCHAR(120),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    descricao TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome_usuario VARCHAR(60) NOT NULL UNIQUE,
    email VARCHAR(200) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    nome_completo VARCHAR(200),
    funcao ENUM('cliente','admin','vendedor') DEFAULT 'cliente',
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_login TIMESTAMP NULL DEFAULT NULL
    );

CREATE TABLE IF NOT EXISTS jogos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(250) NOT NULL,
    slug VARCHAR(220) UNIQUE NOT NULL,
    editora_id BIGINT UNSIGNED NULL,
    data_lancamento DATE,
    preco DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    descricao TEXT,
    url_capa VARCHAR(600),
    qtd_estoque INT DEFAULT 0,
    eh_digital TINYINT(1) DEFAULT 1,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_jogos_editora FOREIGN KEY (editora_id) REFERENCES editoras(id) ON DELETE SET NULL ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS jogo_plataformas (
    jogo_id BIGINT UNSIGNED NOT NULL,
    plataforma_id BIGINT UNSIGNED NOT NULL,
    info_extra VARCHAR(255),
    PRIMARY KEY (jogo_id, plataforma_id),
    CONSTRAINT fk_jp_jogo FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_jp_plataforma FOREIGN KEY (plataforma_id) REFERENCES plataformas(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS jogo_categorias (
    jogo_id BIGINT UNSIGNED NOT NULL,
    categoria_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (jogo_id, categoria_id),
    CONSTRAINT fk_jc_jogo FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_jc_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS enderecos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT UNSIGNED NOT NULL,
    rotulo VARCHAR(80),
    rua VARCHAR(255),
    cidade VARCHAR(120),
    estado VARCHAR(120),
    pais VARCHAR(80),
    cep VARCHAR(40),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_end_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT UNSIGNED NOT NULL,
    status ENUM('pendente','pago','processando','enviado','concluido','cancelado','reembolsado') DEFAULT 'pendente',
    valor_total DECIMAL(12,2) DEFAULT 0.00,
    metodo_pagamento VARCHAR(80),
    endereco_entrega_id BIGINT UNSIGNED NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT fk_pedido_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_pedido_end_entrega FOREIGN KEY (endereco_entrega_id) REFERENCES enderecos(id) ON DELETE SET NULL ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS itens_pedido (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pedido_id BIGINT UNSIGNED NOT NULL,
    jogo_id BIGINT UNSIGNED NOT NULL,
    preco_unitario DECIMAL(12,2) NOT NULL,
    quantidade INT NOT NULL DEFAULT 1,
    subtotal DECIMAL(12,2) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_item_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_item_jogo FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE RESTRICT ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS avaliacoes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT UNSIGNED NOT NULL,
    jogo_id BIGINT UNSIGNED NOT NULL,
    nota TINYINT UNSIGNED NOT NULL CHECK (nota >= 1 AND nota <= 5),
    titulo VARCHAR(250),
    conteudo TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_av_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_av_jogo FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS itens_lista_desejos (
    usuario_id BIGINT UNSIGNED NOT NULL,
    jogo_id BIGINT UNSIGNED NOT NULL,
    adicionado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (usuario_id, jogo_id),
    CONSTRAINT fk_ld_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_ld_jogo FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS descontos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(80) UNIQUE,
    descricao VARCHAR(255),
    percentual_desconto DECIMAL(5,2) CHECK (percentual_desconto >= 0 AND percentual_desconto <= 100),
    inicio_em DATETIME,
    fim_em DATETIME,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS chaves_digitais (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jogo_id BIGINT UNSIGNED NOT NULL,
    item_pedido_id BIGINT UNSIGNED NULL,
    codigo_chave VARCHAR(255) NOT NULL,
    alocado BOOLEAN DEFAULT FALSE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chave_jogo FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_chave_item_pedido FOREIGN KEY (item_pedido_id) REFERENCES itens_pedido(id) ON DELETE SET NULL ON UPDATE CASCADE
    );

CREATE TABLE IF NOT EXISTS historico_precos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    jogo_id BIGINT UNSIGNED NOT NULL,
    preco DECIMAL(12,2) NOT NULL,
    alterado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nota VARCHAR(255),
    CONSTRAINT fk_hp_jogo FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE ON UPDATE CASCADE
    );
